
TYPE_STRING = 'STRING'
TYPE_INTEGER = 'INTEGER'
TYPE_FLOAT = 'FLOAT'
TYPE_BOOLEAN = 'BOOLEAN'
TYPE_TIMESTAMP = 'TIMESTAMP'
TYPE_DATE = 'DATE'
TYPE_TIME = 'TIME'
TYPE_RECORD = 'RECORD'

MODE_NULLABLE = 'NULLABLE'
MODE_REQUIRED = 'REQUIRED'
MODE_REPEATED = 'REPEATED'